on: [push]

name: Docker Image
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/lopezremi/nws_octobre_backend/nodejs:latest
          target: nodejs
 